### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by tcharlss** [tcharlss/griseus2000#2]
Liste de choses à faire :

- [ ] Virer gridle : pas besoin d'une grille complète, remplacer par des `display:flex` et cie là où il faut.
- [ ] Les boutons (`.icone`, boutons de formulaires etc.)
- [ ] Menu principal : responsive à faire, regarder pour le touch, flèches de dépliement.
- [x] Outils rapides : en faire un menu déroulant comme pour le plan.
- [ ] Formulaires : faut-il mettre une largeur max ? (pleine largeur pas pratique pour les textarea par exemple)

**Comment by marcimat** [comment]
Je pense qu’il faut mettre pour les formulaires une largeur max, et de la marge gauche/droite donc si ça dépasse. On écrit du texte dedans 99% du temps, et des lignes longues, c'est pas très pratique pour se relire.

Par ailleurs, je me questionne sur le passage automatique des .editer en 2 colonnes. Dès fois ça fait des trucs un peu bizarre.
